name: Set up environment
description: 'Set up environment variables and dependencies'
inputs:
  ssh-private-key:
    description: 'SSH private key'
    required: true
    default: ''
  tenderly-virtual-mainnet-rpc:
    description: 'Tenderly virtual mainnet RPC'
    required: true
    default: ''
  tenderly-project:
    description: 'Tenderly project'
    required: true
    default: ''
  tenderly-username:
    description: 'Tenderly username'
    required: true
    default: ''
  alchemy-api-key:
    description: 'Alchemy API key'
    required: true
    default: ''
  owner-addr:
    description: 'Owner address'
    required: true
    default: ''
  admin-addr:
    description: 'Admin address'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
        
    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo TENDERLY_VIRTUAL_MAINNET_RPC=${{ inputs.tenderly-virtual-mainnet-rpc }} >> .env
        echo TENDERLY_PROJECT=${{ inputs.tenderly-project }} >> .env
        echo TENDERLY_USERNAME=${{ inputs.tenderly-username }} >> .env
        echo ALCHEMY_API_KEY=${{ inputs.alchemy-api-key }} >> .env
        echo OWNER_ADDR=${{ inputs.owner-addr }} >> .env
        echo ADMIN_ADDR=${{ inputs.admin-addr }} >> .env

    - name: Install dependencies
      shell: bash
      run: npm ci
