name: Run Action and Auth Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'contracts/actions/**'
      - 'contracts/auth/**'

env:
  TENDERLY_AUTOMATIC_VERIFICATION: false
  SUBGRAPH_URL: http://localhost:8000

jobs:
  action-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your project's Node.js version

      - name: Setup Environment
        uses: ./.github/actions/env-setup
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          tenderly-virtual-mainnet-rpc: ${{ secrets.TENDERLY_VIRTUAL_MAINNET_RPC }}
          tenderly-project: ${{ secrets.TENDERLY_PROJECT }}
          tenderly-username: ${{ secrets.TENDERLY_USERNAME }}
          tenderly-api-key: ${{ secrets.TENDERLY_API_KEY }}
          alchemy-api-key: ${{ secrets.ALCHEMY_API_KEY }}
          owner-addr: ${{ secrets.OWNER_ADDR }}
          admin-addr: ${{ secrets.ADMIN_ADDR }}
          SUBGRAPH_URL:
          NEXT_PUBLIC_SUBGRAPH_URL:

      - name: Install Dependencies
        run: npm install

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Run Tests for Changed Actions and Auth
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status

          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"

          # Initialize tracking variables
          declare -A seen_subdirs
          auth_changes=0
          run_all_action_tests=0

          # Iterate through each changed file
          for file in $changed_files; do
            if [[ "$file" == "contracts/actions/ActionBase.sol" || "$file" == contracts/actions/common/* ]]; then
              run_all_action_tests=1
              break  # No need to check other files if we're running all tests
            elif [[ "$file" == contracts/actions/* ]]; then
              # Extract the subdirectory name
              subdir=$(echo "$file" | sed 's|contracts/actions/||' | cut -d'/' -f1)
              # Track unique subdirectories to avoid duplicate test runs
              seen_subdirs["$subdir"]=1
            elif [[ "$file" == contracts/auth/* ]]; then
              auth_changes=1
            fi
          done

          # Function to run tests and handle errors gracefully
          run_tests() {
            local test_command="$1"
            $test_command
          }

          # Run all action tests if ActionBase.sol or common files have changed
          if [[ $run_all_action_tests -eq 1 ]]; then
            echo "Changes detected in ActionBase.sol or common folder. Running all action tests..."
            action_test_files=$(find tests/actions -type f -name "*.test.ts")
            if [[ -n "$action_test_files" ]]; then
              run_tests "npx hardhat test $action_test_files"
            fi
          else
            # Run tests for each changed actions subdirectory
            for subdir in "${!seen_subdirs[@]}"; do
              if [[ -d "tests/actions/$subdir" ]]; then
                subdir_test_files=$(find tests/actions/$subdir -type f -name "*.test.ts")
                if [[ -n "$subdir_test_files" ]]; then
                  run_tests "npx hardhat test $subdir_test_files"
                fi
              fi
            done
          fi

          # If any auth files changed, run all auth tests
          if [[ $auth_changes -eq 1 ]]; then
            # Find all .test.ts files within tests/auth and pass them to Hardhat
            auth_test_files=$(find tests/auth -type f -name "*.test.ts")
            if [[ -n "$auth_test_files" ]]; then
              run_tests "npx hardhat test $auth_test_files"
            fi
          fi
