name: Run Action tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'contracts/actions/**'

jobs:

  action-test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/env-setup
        with:
          ssh-private-key: ${{ secrets.SSH }}
          tenderly-virtual-mainnet-rpc: ${{ secrets.TENDERLY_VIRTUAL_MAINNET_RPC }}
          tenderly-project: ${{ secrets.TENDERLY_PROJECT }}
          tenderly-username: ${{ secrets.TENDERLY_USERNAME }}
          alchemy-api-key: ${{ secrets.ALCHEMY_API_KEY }}
          owner-addr: ${{ secrets.OWNER_ADDR }}
          admin-addr: ${{ secrets.ADMIN_ADDR }}

      - name: Compile contracts
        run: npx hardhat compile
  
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Run tests for changed actions
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"

          for file in $changed_files; do
            if [[ $file == contracts/actions/* ]]; then
              # Extract the subdirectory
              subdir=$(echo $file | sed 's|contracts/actions/||' | cut -d'/' -f1)
              
              # Run tests for the corresponding subdirectory
              echo "Running tests for $subdir"
              npx hardhat test tests/actions/$subdir
            fi
          done
