name: Run Action tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'contracts/actions/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
            cache: 'npm'

      - name: Configure npm
        run: |
          echo "//npm.pkg.github.com/:_authToken=${PAT}" >> .npmrc
        env:
          PAT: ${{ secrets.PAT }}

      - name: Install dependencies
        run: npm ci

      - name: Build athena-sdk
        run: |
          cd node_modules/athena-sdk
          npm run build

      - name: Create .env file
        run: |
          touch .env
          echo TENDERLY_VIRTUAL_MAINNET_RPC=${{ secrets.TENDERLY_VIRTUAL_MAINNET_RPC }} >> .env
          echo TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} >> .env
          echo TENDERLY_USERNAME=${{ secrets.TENDERLY_USERNAME }} >> .env
          echo ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }} >> .env
          echo OWNER_ADDR=${{ secrets.OWNER_ADDR }} >> .env
          echo ADMIN_ADDR=${{ secrets.ADMIN_ADDR }} >> .env

      - name: Compile contracts
        run: npx hardhat compile
  
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Run tests for changed actions
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"

          for file in $changed_files; do
            if [[ $file == contracts/actions/* ]]; then
              # Extract the subdirectory
              subdir=$(echo $file | sed 's|contracts/actions/||' | cut -d'/' -f1)
              
              # Run tests for the corresponding subdirectory
              echo "Running tests for $subdir"
              npx hardhat test tests/actions/$subdir
            fi
          done
  
      - name: Run coverage
        run: npx hardhat coverage


