name: Run Solhint check

on:
  workflow_dispatch:
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/env-setup

      - name: Run lint check
        run: npm run lint