name: Run Solhint check

on:
  workflow_dispatch:
  pull_request:

jobs:
  setup:
    uses: ./.github/workflows/reusable-env-setup.yml

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Run lint check
        run: npm run lint