name: Set up environment

on:
  workflow_call:
    secrets:
      SSH:
        required: true
      TENDERLY_VIRTUAL_MAINNET_RPC:
        required: true
      TENDERLY_PROJECT:
        required: true
      TENDERLY_USERNAME:
        required: true
      ALCHEMY_API_KEY:
        required: true
      OWNER_ADDR:
        required: true
      ADMIN_ADDR:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'
            cache: 'npm'

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH }}
        
      - name: Create .env file
        run: |
          touch .env
          echo TENDERLY_VIRTUAL_MAINNET_RPC=${{ secrets.TENDERLY_VIRTUAL_MAINNET_RPC }} >> .env
          echo TENDERLY_PROJECT=${{ secrets.TENDERLY_PROJECT }} >> .env
          echo TENDERLY_USERNAME=${{ secrets.TENDERLY_USERNAME }} >> .env
          echo ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }} >> .env
          echo OWNER_ADDR=${{ secrets.OWNER_ADDR }} >> .env
          echo ADMIN_ADDR=${{ secrets.ADMIN_ADDR }} >> .env

      - name: Install dependencies
        run: npm ci

    outputs:
      cache-hit: ${{ steps.npm-cache.outputs.cache-hit }}
